package abyss.parallelmultiverse.part07turnbars;

import abyss.lunarengine.Screen;
import abyss.lunarengine.gfx.Bob;
import abyss.lunarengine.sinatra.Sinatra;

public class TurnbarXA extends Turnbar{
	
	public TurnbarXA(Bob bob,Sinatra sinatraMove1,Sinatra sinatraMove2,int positionOffset,boolean fade) {
		this.bob=bob;
		this.sinatraMove1=sinatraMove1;
		this.sinatraMove2=sinatraMove2;
		this.positionOffset=positionOffset;
		if(fade) {
			barStart=-2;
			barEnd=-2;
		}else {
			barStart=Screen.screenSizeX;
			barEnd=Screen.screenSizeX;
		}
		sinatraAnim1=Sinatra.getInstance(new double[]{360.0,2.0,11.0,1.0,0.0,360.0,5.0,2.0,0.0,360.0});//generated by LunarTools Sinus Editor 1.0
		sinatraAnim2=Sinatra.getInstance(new double[]{360.0,2.0,11.0,2.0,0.0,360.0,5.0,1.0,0.0,360.0});//generated by LunarTools Sinus Editor 1.0
	}
	
	public void vbi() {
		if(animPos<bob.bobSizeY-1) {
			animPos++;
		}else {
			animPos=0;
		}
		if(fadeIn) {
			if(barStart>0) {
				barStart-=4;
			}
			if(barEnd<Screen.screenSizeX) {
				barEnd+=4;
			}
		}else if(fadeOut){
			if(barEnd>0) {
				barEnd-=4;
			}
			if(barStart<Screen.screenSizeX) {
				barStart+=4;
			}
		}
	}
	
	public void render() {
		int bobDataFrame=sinatraAnim1.getNextValue(4)+32;
		bobDataFrame=sinatraAnim2.getNextValue(4)+32;

		int b=sinatraMove1.getNextValue(2)+positionOffset+sinatraMove2.getNextValue(1);
		int pixel;
		for(int y=0;y<Screen.screenSizeX;y++) {
			bobDataFrame=sinatraAnim1.getNextDeltaValue(1);
			bobDataFrame+=sinatraAnim2.getNextDeltaValue(2);
			bobDataFrame+=+32;
			if(y>=barStart && y<=barEnd) {
				for(int x=0;x<bob.bobSizeX;x++) {
					pixel=bob.bobdata[bobDataFrame][x+
					                                ((y/2-animPos+(bob.bobSizeY<<3)) % bob.bobSizeY)
					                                *bob.bobSizeX];
					if((pixel & 0xffffff)!=0) {
						render_screendataWorking[y+(b+x)*Screen.screenSizeX]=pixel;
					}
				}
			}
			b=sinatraMove1.getNextDeltaValue(1)+positionOffset+sinatraMove2.getNextDeltaValue(2);
		}
	}
	
}
